'use strict';

const minify = require('html-minifier').minify;
const mkdirp = require('mkdirp');
const fs = require('fs');

const DEFAULT_PATTERN = /\.html$/;
const DEFAULT_HTMLMIN_OPTIONS = {
  caseSensitive: false,
  collapseBooleanAttributes: true,
  collapseInlineTagWhitespace: false,
  collapseWhitespace: true,
  conservativeCollapse: false,
  html5: true,
  includeAutoGeneratedTags: false,
  keepClosingSlash: false,
  minifyCSS: true,
  minifyJS: true,
  preserveLineBreaks: false,
  preventAttributesEscaping: false,
  processConditionalComments: true,
  removeAttributeQuotes: true,
  removeComments: true,
  removeEmptyAttributes: true,
  removeOptionalTags: true,
  removeScriptTypeAttributes: true,
  removeStyleLinkTypeAttributes: true,
  sortAttributes: true,
  sortClassName: true
};

class HtmlPages {
  constructor(config) {
    if (config === undefined) config = {};
    if (config.plugins === undefined) config.plugins = {};

    const pluginConfig = config.plugins.htmlPages || {};
    this.disabled = !config.optimize || pluginConfig.disabled;
    this.pattern = pluginConfig.pattern || DEFAULT_PATTERN;
    this.htmlMinOptions = pluginConfig.htmlMin ?
      Object.assign({}, pluginConfig.htmlMin) :
      DEFAULT_HTMLMIN_OPTIONS;
  }

  compileStatic(file) {
    return new Promise((resolve, reject) => {
      fs.readFile(file.path, 'utf8', (err, data) => {
        const result = this.disabled ? data : minify(data, this.htmlMinOptions);
        if (err) return reject(err);
        resolve(result);
      });
    });
  }
}

HtmlPages.prototype.brunchPlugin = true;
HtmlPages.prototype.type = 'template';
HtmlPages.prototype.extension = 'html';
HtmlPages.prototype.staticTargetExtension = 'html';

module.exports = HtmlPages;
